### PR TITLE
Code academy suggestion box

### PR DESCRIPTION
**Pull request by benmcosker**
Initial project commit as a PR for the Code Academy final project.  This now has the corrected README.md and package.json so that `lite-server` is installed and referenced correctly.

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
@benmcosker 
Not sure what's going on here, but why are there 22 commits and 7000 files changed?  Per #1 , shouldn't there just be one change, to README.md?

**Comment by benmcosker** [comment]
@obuckley-kenzan - I can do that, the change was adding node_modules to `.gitignore`, as they were being included in the repo.  I was first trying to set up the repo with just the `gitignore`, `README.md` and `package.json`, and then I will do a PR with the project.  That would be the the correct flow... set up repo, then project files, correct?

**Comment by obuckley-kenzan** [comment]
Not sure I follow.  As you have everything in master already setup, why do you need to recommit all these changes?  My recommendation was just to update the README, hence why I would only expect one commit / one file change here.

**Comment by benmcosker** [comment]
I had the repo pointing to a branch (code-academy-suggestion-box) and not master. I have gone into settings and changed that. Yes, I am learning a lot about setting up a repo, unfortunately this is proving to be a little too involved.

**Comment by obuckley-kenzan** [comment]
Interesting.  I don't see this as a fork of that repo, so my take on it was that you were making all changes locally without an upstream as a personal repo, just making changes as you go

My recommendation would be to:

1. Close this PR, and in your local repo
2. Switch to master
3. Get latest changes  (make sure there are NO local changes
4. Make a new branch
5. Make changes to the README
6. Commit and push
7. Open a new PR

**Pull request closed without merging**
